variables:
    NODE_VERSION: "20.19.4"
    # 确保 corepack 可用（node:lts 已包含 corepack）
    PNPM_VERSION: "10.14.0"
    # 本地 pnpm store
    PNPM_STORE_DIR: "$CI_PROJECT_DIR/.pnpm-store"
    YARN_VERSION: "1.22.22"
    YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/.yarn/cache"
    # 缓存过期时间
    CACHE_EXPIRE: "7d"
    # artifact 过期时间
    ARTIFACT_EXPIRE: "1d"
    GIT_CLEAN_FLAGS: '-ffdx --exclude=node_modules_4d' # 排除指定目录
    APP_NAME: "LearnWebGL"
    DIST_ZIP_FILE_NAME: "dist.tar.gz"

default:
  image: "node:$NODE_VERSION"

stages:
    - prepare
    - install
    - test
    - build
    - deploy

cache:
    key:
        files:
          - pnpm-lock.yaml
    paths:
        - node_modules/
    policy: pull-push

.prepare-yarn: &prepare-yarn |
  npx corepack enable
  npx corepack prepare yarn@${YARN_VERSION} --activate
  node -v
  yarn -v

.prepare-pnpm: &prepare-pnpm |
  npx corepack enable
  npx corepack prepare pnpm@${PNPM_VERSION} --activate
  node -v
  pnpm -v

# 常规规则
.rules-standard: &rules-standard
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "build-cicd"'
      when: on_success
    - when: never

# 匹配开发分支
.rules-develop: &rules-develop
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: on_success
    - when: never

# 匹配发布分支
.rules-release: &rules-release
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main"'
      when: on_success
    - when: never



prepare:
    stage: prepare
    extends:
      - .rules-standard
    variables:
        GIT_STRATEGY: clone # 仅此阶段克隆
    script:
        - echo "Prepare stage"
        - echo "CI_PROJECT_DIR=$CI_PROJECT_DIR"
    rules:
        - if: $CI_PIPELINE_SOURCE

install:
    stage: install
    extends:
        - .rules-standard
    before_script:
        - *prepare-pnpm
        - echo "CI_PROJECT_DIR=$CI_PROJECT_DIR"
    script:
        - echo "Install stage"
        - |
          if [ -f pnpm-lock.yaml ]; then
            echo "Using pnpm (lockfile detected)"
            pnpm install --frozen-lockfile
          fi


test:
    stage: test
    extends:
        - .rules-standard
    dependencies:
        - install
    before_script:
      - *prepare-pnpm
      - echo "CI_PROJECT_DIR=$CI_PROJECT_DIR"
    script:
        - echo "Test step"
        - npx eslint ./src --cache

build:
    stage: build
    extends:
      - .rules-standard
    dependencies:
      - install
    before_script:
      - *prepare-pnpm
      - echo "CI_PROJECT_DIR=$CI_PROJECT_DIR"
    script:
      - echo "Build step"
      - |
        if [ -f pnpm-lock.yaml ]
        then
          pnpm -s build
        fi
      - |
        if [ -d dist ]
        then
          echo "Create zip file"
          tar -zcf $DIST_ZIP_FILE_NAME -C dist .
        else
          echo "no project"
        fi
    artifacts:
      name: "${APP_NAME}-${CI_COMMIT_SHORT_SHA}"
      paths:
        - $DIST_ZIP_FILE_NAME
        - dist/
      expire_in: 1d
      when: on_success

deploy-to-test:
  stage: deploy
  extends: .rules-develop
  dependencies:
    - build
  variables:
    GIT_STRATEGY: none
  before_script:
    - *prepare-pnpm
    - echo "CI_PROJECT_DIR=$CI_PROJECT_DIR"
  script:
    - echo "Deploy to test"
    - |
      if [ -f $DIST_ZIP_FILE_NAME ] ;
      then
        echo "exist $DIST_ZIP_FILE_NAME"
        git -v
        git branch -av
      fi

deploy-to-release:
  stage: deploy
  extends: .rules-release
  dependencies:
    - build
  variables:
    GIT_STRATEGY: none
  before_script:
    - *prepare-pnpm
    - echo "CI_PROJECT_DIR=$CI_PROJECT_DIR"
  script:
    - echo "Deploy to test"
    - |
      if [ -f $DIST_ZIP_FILE_NAME ] ;
      then
        echo "exist $DIST_ZIP_FILE_NAME"
        git -v
        git branch -av
      fi
